sudo: required
language: generic

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-215744953535'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
